name: Manual Deployment
run-name: Manual Deployment started by ${{ github.actor }}

on:
  workflow_dispatch:
      inputs: 
        environment:
          description: 'Environment to deploy'
          type: choice
          options: ['dev', 'stage', 'production']
          required: true
          default: 'stage'

jobs:
  Deploy_to_environment:
    uses: JoelYoung01/Templates/.github/workflows/DeployStaticS3Sitel.yaml@main
    with:
      environment: ${{ github.event.inputs.environment }}
      app_name: ${{ vars.APP_NAME }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
